szoveg=str(input())
szoveg=szoveg.replace("a", "e")
szoveg=szoveg.replace("á", "e")
szoveg=szoveg.replace("é", "e")
szoveg=szoveg.replace("o", "e")
szoveg=szoveg.replace("ó", "e")
szoveg=szoveg.replace("ö", "e")
szoveg=szoveg.replace("ő", "e")
szoveg=szoveg.replace("u", "e")
szoveg=szoveg.replace("ú", "e")
szoveg=szoveg.replace("ü", "e")
szoveg=szoveg.replace("ű", "e")
szoveg=szoveg.replace("i", "e")
szoveg=szoveg.replace("í", "e")
print(szoveg)